//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolSCSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SchoolSCSystemEntities : DbContext
    {
        public SchoolSCSystemEntities()
            : base("name=SchoolSCSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ApprovalData> ApprovalData { get; set; }
        public DbSet<ApprovalNode> ApprovalNode { get; set; }
        public DbSet<ApprovalNode_User> ApprovalNode_User { get; set; }
        public DbSet<ApprovalProcess> ApprovalProcess { get; set; }
        public DbSet<Class> Class { get; set; }
        public DbSet<Course> Course { get; set; }
        public DbSet<Course_Teacher> Course_Teacher { get; set; }
        public DbSet<Log> Log { get; set; }
        public DbSet<Major> Major { get; set; }
        public DbSet<Menu> Menu { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<Role_Menu> Role_Menu { get; set; }
        public DbSet<Score> Score { get; set; }
        public DbSet<Student> Student { get; set; }
        public DbSet<Teacher> Teacher { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<User_Role> User_Role { get; set; }
        public DbSet<ClassRoom> ClassRoom { get; set; }
        public DbSet<ClassRoom_User> ClassRoom_User { get; set; }
        public DbSet<Leave> Leave { get; set; }
    }
}
